name: docker-cd

on:
  workflow_run:
    workflows: ["maven-ci"]
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: maven-artifact
          path: maven-artifact
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/warehouse-api:latest
